notifications:
  email:
    recipients:
      - amdouni.hamza.hsn@gmail.com

    on_success: change
    on_failure: always

language: node_js

node_js:
  - 12

install:
  - npm i

cache:
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm i

script:
  - npm i
  - npm run test
  - npm run build:client
